baseURL = 'https://blog.lex.la/'
languageCode = 'en-us'
title = 'blog.lex.la'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "blog.lex.la"
description = "Personal blog"
author = "Aleksei Sviridkin"

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/lexfrei"

[[params.socialIcons]]
name = "email"
url = "mailto:f@lex.la"

[params.homeInfoParams]
Title = "blog.lex.la"
Content = "Personal blog about SRE, DevOps, and other tech stuff"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
