baseURL = 'https://blog.lex.la/'
theme = 'PaperMod'
defaultContentLanguage = 'en'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
author = "Aleksei Sviridkin"

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/lexfrei"

[[params.socialIcons]]
name = "email"
url = "mailto:f@lex.la"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "blog.lex.la"

    [languages.en.params]
      description = "Personal blog about SRE, DevOps, and other tech stuff"

    [languages.en.params.homeInfoParams]
      Title = "blog.lex.la"
      Content = "Personal blog about SRE, DevOps, and other tech stuff"

  [languages.ru]
    languageName = "Русский"
    languageCode = "ru-ru"
    weight = 2
    title = "blog.lex.la"

    [languages.ru.params]
      description = "Личный блог про SRE, DevOps и другие технологии"

    [languages.ru.params.homeInfoParams]
      Title = "blog.lex.la"
      Content = "Личный блог про SRE, DevOps и другие технологии"
